---
- name: Create Postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ root_user.name }}"
    password: "{{ root_user.password }}"
    role_attr_flags: "SUPERUSER,CREATEROLE,CREATEDB,INHERIT,login"
    state: present

- name: Restart Postgresql on Debian
  service: name={{ postgresql_service_name }} state=restarted
  #notify:
  # - restart postgresql-ubuntu
  when: ansible_os_family == 'Debian'

- name: initdb on CentOs
  action: shell service postgresql-{{ postgresql_version }} initdb
  when: ansible_distribution_release == 'CentOs'

- name: chkconfig on CentOs
  action: shell chkconfig postgresql-{{ postgresql_version }} on service postgresql-{{ postgresql_version }} start
  when: ansible_distribution_release == 'CentOs'