---
- name: Restart Postgresql on Debian
  service: name={{ postgresql_service_name }} state=restarted
  when: ansible_os_family == 'Debian'
- name: initdb on Red Hat
  action: shell service postgresql-{{ postgresql_version }} initdb
  when: ansible_os_family == 'RedHat' 

- name: Start automatically when the OS starts on Red Hat
  action: shell chkconfig postgresql-{{ postgresql_version }} on service postgresql-{{ postgresql_version }} start
  when: ansible_os_family == 'RedHat' 

- name: Restart Postgresql on Debian
  service: name=postgresql-{{ postgresql_version }} state=restarted
  when: ansible_os_family == 'RedHat' 

- name: Create database 
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present
  when: create_db == 'yes'

- name: Create Postgresql user
  sudo_user: postgres
  postgresql_user:
    name: "{{ root_user.name }}"
    password: "{{ root_user.password }}"
    role_attr_flags: "SUPERUSER,CREATEROLE,CREATEDB,INHERIT,LOGIN,REPLICATION"
    state: present
