---
# Debian
- name: Add key on Debian
  apt_key: url='https://www.postgresql.org/media/keys/ACCC4CF8.asc' state=present
  when: ansible_os_family == 'Debian'

- name: Add repository on Debian
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' state=present
  when: ansible_os_family == 'Debian'

- name: Install PostgreSQL on Debian
  apt: name=python-psycopg2,postgresql-{{ postgresql_version }} state=present update_cache=yes
  when: ansible_os_family == 'Debian'

# Centos  
- name: Format postgresql_version
  action: shell echo {{postgresql_version}}
  register: result

- name:  Yum rpm from CentOs 6
  #https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6-x86_64/pgdg-centos96-9.6-3.noarch.rpm
  #https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-3.noarch.rpm
  #https://download.postgresql.org/pub/repos/yum/9.2/redhat/rhel-6-x86_64/pgdg-oraclelinux92-9.2-9.noarch.rpm
  yum: name=https://download.postgresql.org/pub/repos/yum/{{ postgresql_version }}/redhat/rhel-6-x86_64/pgdg-centos{{result.stdout.split('.')[0]}}{{result.stdout.split('.')[1]}}-{{ postgresql_version }}-3.noarch.rpm state=present
  #yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present
  when: ansible_os_family == 'RedHat' 
  ignore_errors: yes

- name: Install PostgreSQL on Red Hat
  yum: name=python-psycopg2,postgresql{{ result.stdout.split('.')[0] }}{{result.stdout.split('.')[1]}}-server,postgresql{{result.stdout.split('.')[0]}}{{result.stdout.split('.')[1]}}-contrib state=present
  when: ansible_os_family == 'RedHat' 
  ignore_errors: yes
