- name: restart postgresql-ubuntu
  action: shell service {{ postgresql_service_name }} stop; service {{ postgresql_service_name }} start
  when: ansible_os_family == 'Debian'


# - name: restart postgresql-centOs
#   action: shell service postgresql-{{ postgresql_version}}{{ postgresql_service_name }} stop; service {{ postgresql_service_name }} start
#   when: ansible_distribution == 'CentOS' 


# yum install postgresql95-server postgresql95-contrib
# (or yum groupinstall "PostgreSQL Database Server 9.6 PGDG")
# service postgresql-9.5 initdb
# chkconfig postgresql-9.5 on service postgresql-9.5 start
